using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using ICM.Model;
using ICM.Utils;
using NLog;

namespace ICM.Dao
{
    public class InstitutionsDAO
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        /// <summary>
        /// Adds an insitution to the database.
        /// </summary>
        /// <param name="institution">Institution to be added.</param>
        /// <returns>The institutin's ID automatically generated by the database.</returns>
        public int AddInstitution(Institution institution)
        {
            int institutionId;

            Logger.Debug("Creating institution in database");

            var parametersInstitution = new NameValueCollection
            {
                {"@name", institution.Name},
                {"@description", institution.Description},
                {"@city", institution.City},
                {"@interest", institution.Interest},
                {"@languageName", institution.Language.Name},
                {"@countryName", institution.Country.Name},
                {"@archived", "0"}
            };

            //TODO: is the right isolation level for christ's sake??? and check all the rest of the document!
            SqlTransaction transaction = DBUtils.BeginTransaction(IsolationLevel.ReadUncommitted);

            //Insert institution
            institutionId = DBUtils.ExecuteTransactionInsert(
                "INSERT INTO [Institution] (name,description,city,interest,languageName,countryName,archived) VALUES (@name,@description,@city,@interest,@languageName,@countryName,@archived)",
                transaction, parametersInstitution, "Institution");

            //Insert departments
            foreach (Department department in institution.Departments)
            {
                var parametersDepartment = new NameValueCollection
                {
                    {"@name", department.Name},
                    {"@institutionId", institutionId.ToString()},
                    {"@archived", "0"}
                };
                DBUtils.ExecuteTransactionInsert(
                    "INSERT INTO [Department] (name,institutionId,archived) VALUES (@name,@institutionId,@archived)",
                    transaction, parametersDepartment, "Department");
            }

            transaction.Commit();

            Logger.Debug("Created institution with id {0} in database", institutionId);

            return institutionId;
        }

        /// <summary>
        /// Creates an institution's instance representing the institution stored in the database with the specified ID.
        /// </summary>
        /// <param name="id">ID of the institution stored in the database.</param>
        /// <returns>Institution's instance.</returns>
        public Institution GetInstitution(int id)
        {
            Institution institution = null;

            Logger.Debug("Retrieving institution with id {0} from database", id);

            var parameters = new NameValueCollection
            {
                {"@id", id.ToString()},
            };

            var transaction = DBUtils.BeginTransaction(IsolationLevel.ReadUncommitted);

            using (var institutionReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Institution] WHERE id = @id", transaction, parameters))
            {
                if(institutionReader.Read())
                {
                    institution = GetInstitutionWithoutDepartmentsAndContinent(institutionReader);
                }
            }

            if(institution != null)
            {
                institution.Departments = GetDepartments(institution.Id, transaction);
                institution.Country.Continent = GetContinent(institution.Country.Name, transaction);
            }

            transaction.Commit();

            Logger.Debug("Retrieved institution with id {0} from database", id);

            return institution;
        }

        ///<summary>
        /// Return the institution with the given id. This method opens a connection and close it. 
        ///</summary>
        ///<param name="id">The id of the institution to search. </param>
        ///<returns>The institution with the given id. </returns>
        public Institution GetInstitutionClean(int id)
        {
            Logger.Debug("Retrieving institution with id {0} from database", id);

            using(var connection = DBManager.GetInstance().GetNewConnection())
            {
                return GetInstitution(id, connection);
            }
        }

        public Institution GetInstitution(int id, SqlConnection connection)
        {
            Institution institution = null;

            var parameters = new NameValueCollection
            {
                {"@id", id.ToString()},
            };

            var transaction = connection.BeginTransaction(IsolationLevel.ReadUncommitted);

            using (var institutionReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Institution] WHERE id = @id", transaction, parameters))
            {
                if (institutionReader.Read())
                {
                    institution = GetInstitutionWithoutDepartmentsAndContinent(institutionReader);
                }
            }

            if (institution != null)
            {
                institution.Departments = GetDepartments(institution.Id, transaction);
                institution.Country.Continent = GetContinent(institution.Country.Name, transaction);
            }

            transaction.Commit();

                Logger.Debug("Retrieved institution with id {0} from database", id);

            return institution;
        }

        //TODO: add transaction as parameter
        public void UpdateInstitution(Institution institution)
        {
            SqlConnection connection = DBManager.GetInstance().GetConnection();
            SqlTransaction transaction = DBUtils.BeginTransaction(IsolationLevel.ReadUncommitted);
            NameValueCollection parameters;

            List<Department> oldDepartments = GetDepartments(institution.Id, transaction);  //Department already present in DB

            Logger.Debug("Archiving old departments of institution with id {0} in database", institution.Id);

            //Delete all the old departments
            foreach(Department oldDepartment in oldDepartments)
            {
                if (!institution.Departments.ContainsDepartmentWithName(oldDepartment.Name))
                {
                    parameters = new NameValueCollection
                    {
                        {"@departmentId", oldDepartment.Id.ToString()},
                    };
                    DBUtils.ExecuteNonQuery(
                        "DELETE FROM [Department] WHERE id=@departmentId",
                        transaction,
                        parameters);
                }
            }

            Logger.Debug("Archived old departments of institution with id {0} in database", institution.Id);

            Logger.Debug("Adding new departments of institution with id {0} into database", institution.Id);

            //Add all the new departments
            foreach(Department department in institution.Departments)
            {
                if (!oldDepartments.ContainsDepartmentWithName(department.Name))
                {
                    parameters = new NameValueCollection
                    {
                        {"@name", department.Name},
                        {"@institutionId", institution.Id.ToString()},
                        {"@archived", "0"}
                    };
                    DBUtils.ExecuteNonQuery(
                        "INSERT INTO [Department] (name,institutionId,archived) VALUES (@name,@institutionId,@archived)",
                        transaction,
                        parameters);
                }
            }

            Logger.Debug("Added new departments of institution with id {0} into database", institution.Id);

            //Update institution data
            parameters = new NameValueCollection
            {
                {"@institutionId", institution.Id.ToString()},
                {"@name", institution.Name},
                {"@description", institution.Description},
                {"@city", institution.City},
                {"@interest", institution.Interest},
                {"@languageName", institution.Language.Name},
                {"@countryName", institution.Country.Name},
                {"@archived", "0"}
            };

            Logger.Debug("Updating information of institution with id {0} in database", institution.Id);

            DBUtils.ExecuteNonQuery(
                "UPDATE [Institution] SET name = @name, description = @description, city = @city, interest = @interest, languageName = @languageName, countryName = @countryName WHERE id = @institutionId",
                transaction,
                parameters);

            Logger.Debug("Updated information of institution with id {0} in database", institution.Id);

            //Commit transaction
            transaction.Commit();
        }

        /// <summary>
        /// Creates and fills a list with all the institutions stored in the database.
        /// </summary>
        /// <returns>The list of institutions.</returns>
        public List<Institution> GetInstitutions()
        {
            List<Institution> institutions = new List<Institution>();
            SqlTransaction transaction = DBUtils.BeginTransaction(IsolationLevel.ReadUncommitted);

            Logger.Debug("Retrieving all the institutions from database");

            //Instantiate institutions without department list
            using (SqlResult institutionReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Institution]", transaction))
            {
                while (institutionReader.Read())
                {
                    institutions.Add(GetInstitutionWithoutDepartmentsAndContinent(institutionReader));
                }
            }

            Logger.Debug("Retrieved all the institutions from database");

            Logger.Debug("Retrieving all the departments from database");

            //Add department list to the institutions
            foreach (Institution institution in institutions)
            {
                institution.Departments = GetDepartments(institution.Id, transaction);
                institution.Country.Continent = GetContinent(institution.Country.Name, transaction);
            }

            transaction.Commit();

            return institutions;
        }

        public List<Institution> GetInstitutions(SqlConnection connection)
        {
            var institutions = new List<Institution>();
            var transaction = connection.BeginTransaction(IsolationLevel.ReadUncommitted);

            //Instantiate institutions without department list
            using (var institutionReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Institution]", transaction))
            {
                while (institutionReader.Read())
                {
                    institutions.Add(GetInstitutionWithoutDepartmentsAndContinent(institutionReader));
                }
            }

            //Add department list to the institutions
            foreach (var institution in institutions)
            {
                institution.Departments = GetDepartments(institution.Id, transaction);
                institution.Country.Continent = GetContinent(institution.Country.Name, transaction);
            }

            transaction.Commit();

            Logger.Debug("Retrieved all the departments from database");
            
            return institutions;
        }

        ///<summary>
        /// Returns all the institutions. This method opens a new connection and close it. 
        ///</summary>
        ///<returns>All the institutions of the database. </returns>
        public List<Institution> GetInstitutionsClean()
        {

            using(var connection = DBManager.GetInstance().GetNewConnection())
            {
                return GetInstitutionsClean(connection);
            }
        }

        public List<Institution> GetInstitutionsClean(SqlConnection connection)
        {
            var institutions = new List<Institution>();

            var transaction = connection.BeginTransaction(IsolationLevel.ReadUncommitted);

                Logger.Debug("Retrieving all the institutions from database");

            //Instantiate institutions without department list
            using (var institutionReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Institution]", transaction, new NameValueCollection()))
            {
                while (institutionReader.Read())
                {
                    institutions.Add(GetInstitutionWithoutDepartmentsAndContinent(institutionReader));
                }
            }

                Logger.Debug("Retrieved all the institutions from database");

                Logger.Debug("Retriving all the departments from database");

            //Add department list to the institutions
            foreach (var institution in institutions)
            {
                institution.Departments = GetDepartments(institution.Id, transaction);
                institution.Country.Continent = GetContinent(institution.Country.Name, transaction);
            }

            transaction.Commit();

                Logger.Debug("Retrieved all the departments from database");

            return institutions;
        }

        /// <summary>
        /// Creates and fills the list of all the departments of the institutions specified by institutionId.
        /// </summary>
        /// <param name="institutionId">Institution's id.</param>
        /// <returns>The list of departments.</returns>
        public List<Department> GetDepartments(int institutionId) {
            Logger.Debug("Retrieving the departments of the institution with id {0} from database", institutionId);
            SqlTransaction transaction = DBUtils.BeginTransaction(IsolationLevel.ReadUncommitted);
            List<Department> departments = GetDepartments(institutionId, transaction);
            transaction.Commit();
            Logger.Debug("Retrieved the departments of the institution with id {0} from database", institutionId);
            return departments;
        }

        public void ArchiveInstitution(int id)
        {
            var parameters = new NameValueCollection
            {
                {"@id", id.ToString()}
            };

            Logger.Debug("Archiving the institution with id {0} in database", id);

            DBUtils.ExecuteUpdate(
                "UPDATE [Institution] SET archived = 1 WHERE id = @id",
                IsolationLevel.ReadUncommitted, parameters);

            Logger.Debug("Archived the institution with id {0} in database", id);
        }

        /// <summary>
        /// Creates an institution having the departments list and the continent attributes not instanciated yet.
        /// </summary>
        /// <param name="institutionReader">An SqlResult instance used by the function to query the database.</param>
        /// <returns>The institution</returns>
        private static Institution GetInstitutionWithoutDepartmentsAndContinent(SqlResult institutionReader)
        {
            //Instantiate institution
            return new Institution( (int) institutionReader["id"],
                                    (string) institutionReader["name"],
                                    (string) institutionReader["description"],
                                    (string) institutionReader["city"],
                                    (string) institutionReader["Interest"],
                                    new Language { Name = (string) institutionReader["languageName"] },
                                    new Country { Name = (string)institutionReader["countryName"] }, 
                                    null,
                                    (bool) institutionReader["archived"]);
        }

        /// <summary>
        /// Creates and fill a list of departments belonging to the institution identified by insitutionId.
        /// </summary>
        /// <param name="institutionId">The institution's identifier.</param>
        /// <param name="transaction">The transaction to be used to query the database.</param>
        /// <returns>The department's list.</returns>
        private List<Department> GetDepartments(int institutionId, SqlTransaction transaction)
        {
        /// <summary>
        /// Creates and fill a list of departments belonging to the institution identified by insitutionId.
        /// </summary>
        /// <param name="institutionId">The institution's identifier.</param>
        /// <param name="connection">The connection to be used to query the database.</param>
        /// <param name="transaction">The transaction to be used to query the database.</param>
        /// <returns>The department's list.</returns>
            List<Department> departments = new List<Department>();

            var parameters = new NameValueCollection
            {
                {"@institutionId", institutionId.ToString()}
            };

            using (SqlResult departmentReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Department] WHERE institutionId = @institutionId", transaction, parameters))

            {
                //Fill departments list
                while (departmentReader.Read())
                {
                    Department department = new Department();
                    department.Id = (int)departmentReader["id"];
                    department.Name = (string)departmentReader["name"];
                    departments.Add(department);
                }
            }

            Logger.Debug("Retrived department of the institution with id {0} in database", institutionId);

            return departments;
        }

        /// <summary>
        /// Creates continent to which the country identified by countryName belongs.
        /// </summary>
        /// <param name="countryName">The country's identifier.</param>
        /// <param name="transaction">The transaction to be used to query the database.</param>
        /// <returns>The continent instance.</returns>
        private Continent GetContinent(string countryName, SqlTransaction transaction)
        {
        /// <summary>
        /// Creates continent to which the country identified by countryName belongs.
        /// </summary>
        /// <param name="countryName">The country's identifier.</param>
        /// <param name="connection">The connection to be used to query the database.</param>
        /// <param name="transaction">The transaction to be used to query the database.</param>
        /// <returns>The continent instance.</returns>
            //Get continent name
            string continentName;
            var parameters = new NameValueCollection
            {
                {"@countryName", countryName}
            };

            using (SqlResult countryReader = DBUtils.ExecuteTransactionQuery("SELECT * FROM [Country] WHERE name = @countryName", transaction, parameters))
            {
                countryReader.Read();
                continentName = (string)countryReader["continentName"];
            }

            Logger.Debug("Retrieved continent of the country named {0} from database", countryName);

            //Instantiate continent
            return new Continent() { Name = continentName };
        }

        /// <summary>
        /// Search for institutions in the database using the given arguments as criteria
        /// </summary>
        /// <param name="name">Instution name</param>
        /// <param name="language">Institution language</param>
        /// <param name="continent">Institution country</param>
        /// <param name="country">Institution country</param>
        /// <param name="archived">Institution state (archived or not)</param>
        /// <returns>All the institutions matching the search criteria</returns>
        public List<Institution> SearchInstitutions(string name, string language, string continent, string country, bool archived)
        {
            List<Institution> institutions = new List<Institution>();
            var parameters = new NameValueCollection
            {
                {"@name", "%" + name + "%"},
                {"@languageName", "%" + language + "%"},
                {"@countryName", "%" + country + "%"},
                {"@continentName", continent}
            };

            // Create query string
            string query =  "SELECT * FROM [Institution] WHERE name LIKE(@name) AND languageName LIKE(@languageName)";
            
            if (!archived)
            {
                query += " AND archived = 0";
            }

            if (country != "")
            {
                query += " AND countryName LIKE(@countryName)";
            }
            else if (continent != "")
            {
                query += " AND countryName IN (SELECT name FROM country WHERE continentName = @continentName)";
            }

            Logger.Debug("Retrieving institutions with name like {0}, language={1}, continent={2}, country={3}, archived={4} from database",
                            name,
                            language,
                            continent,
                            country,
                            archived);

            //Start transaction
            SqlTransaction transaction = DBUtils.BeginTransaction(IsolationLevel.ReadUncommitted);

            //Instantiate institutions without department list
            using (SqlResult institutionReader = DBUtils.ExecuteTransactionQuery(query, transaction, parameters))
            {
                while (institutionReader.Read())
                {
                    institutions.Add(GetInstitutionWithoutDepartmentsAndContinent(institutionReader));
                }
            }

            //Add department list to the institutions
            foreach (Institution institution in institutions)
            {
                institution.Departments = GetDepartments(institution.Id, transaction);
                institution.Country.Continent = GetContinent(institution.Country.Name, transaction);
            }

            //End transaction
            transaction.Commit();

            Logger.Debug("Retrived institutions with name like {0}, language={1}, continent={2}, country={3}, archived={4} from database",
                            name,
                            language,
                            continent,
                            country,
                            archived);

            return institutions;
        }

        /// <summary>
        /// Creates an instance of the department identified by id, which is stored in the database.
        /// </summary>
        /// <param name="id">The department's identifier.</param>
        /// <returns>The department's instance.</returns>
        public Department GetDepartmentById(int id, SqlConnection connection)
        {
            var departments = new List<Department>();

            var transaction = connection.BeginTransaction(IsolationLevel.ReadUncommitted);

            var parameters = new NameValueCollection
            {
                {"@id", id.ToString()},
            };

            Logger.Debug("Retriving department with id {0} from database", id);

            using (var readerDestination = DBUtils.ExecuteTransactionQuery("SELECT D.id AS depId, d.name AS depName, I.id AS institutionId, I.name AS insName, I.city, I.languageName, I.countryName" +
                                                     " FROM [Department] D" +
                                                     " INNER JOIN [Institution] I" +
                                                     " ON D.institutionId = I.id" +
                                                     " WHERE D.id = @id"
                                                    , transaction, parameters))
            {
                while (readerDestination.Read())
                {
                    Department d = new Department();
                    d.Id = (int)readerDestination["depId"];
                    d.Name = (string)readerDestination["depName"];
                    d.InstitutionName = (string)readerDestination["insName"];
                    d.InstitutionId = (int)readerDestination["institutionId"];
                    d.InstitutionCity = (string)readerDestination["city"];
                    d.InstitutionCountry = (string)readerDestination["countryName"];
                    d.InstitutionLanguage = (string)readerDestination["languageName"];
                    departments.Add(d);
                }
            }

            transaction.Commit();

            Logger.Debug("Retrieved department with id {0} from database", id);

            return departments.First();
        }
    }
}